### ISSUE TITLE
pylint raises import errors

### ISSUE THREAD

**Issue by hm1298** [naomiburks/hanabdata#3]
pylint raised import errors on almost all of our inter-package imports, which did work correctly when ran. This thread outlines why it may be a good thing for pylint to catch, but since \_\_init\_\_.py was empty, running "correctly" did nothing: [https://stackoverflow.com/questions/51095449/pylint-false-positive-e0401-import-errors-in-vscode-while-using-venv/51236340#51236340](https://stackoverflow.com/questions/51095449/pylint-false-positive-e0401-import-errors-in-vscode-while-using-venv/51236340#51236340).

So I've deleted \_\_init\_\_.py for now, hope that doesn't break anything? [The documentation](https://docs.python.org/3/reference/import.html#regular-packages) seems to suggest it shouldn't matter

Also, PEP8's [suggestions on imports](https://peps.python.org/pep-0008/#imports) makes it sound like we are correct to import as we currently do.

**Comment by naomiburks** [comment]
Deleting __init__.py as a current solution makes sense

**Comment by naomiburks** [comment]
I think I'll close this...? I don't 100% understand the problem/solution, but it seems resolved, at least for now.
