### ISSUE TITLE
pylint doesn't like single character variable names

### ISSUE THREAD

**Issue by naomiburks** [naomiburks/hanabdata#4]
Pylint is raising issues for single-character variable names but I think a lot of their uses in the project are OK. To make pylint happy while still using single-character names we need to add a [pylintrc file](https://stackoverflow.com/questions/21833872/why-does-pylint-object-to-single-character-variable-names), I'll look into [doing this](https://stackoverflow.com/questions/22448731/how-do-i-create-a-pylintrc-file) next time I'm coding.

**Comment by hm1298** [comment]
I agree, and PEP8 even seems to differ from pylint on when it is acceptable: see [documentation](https://peps.python.org/pep-0008/#programming-recommendations)

**Comment by naomiburks** [comment]
I added the pylint file, so this should be resolved now.
