### ISSUE TITLE
update.py does not only update

### ISSUE THREAD

**Issue by hm1298** [naomiburks/hanabdata#5]
Currently, update.py simply rewrites the existing files as if nothing had been downloaded previously. For very large sets of games, this requires too many calls to Hanab Live API and slows down performance. (For instance, updating Lanvin when there is nothing to update takes 200 seconds, when it should take <5 seconds.)

I'm just noting this now because we will see performance improvements when I rewrite fetch.py to paginate /history-full/ in an acceptable way, but that won't address the root issue

**Comment by naomiburks** [comment]
The easiest thing I can think of to limit redundant calls is to keep a record of the last time each user's full data got successfully updated.

**Comment by naomiburks** [comment]
I realized that if we can keep JSONs sorted reverse chronologically, we can open them to find the last game we have, use that as a start ID for the API call, then append our prior JSON data to that. I implemented this and wrote a catch to paginate if the server doesn't respond in time -- currently pagination is implemented very badly and will revert to overwriting all games.

**Comment by hm1298** [comment]
leaving open until one of us fixes the pagination of /history-full/<player> since it doesn't work for me currently (and we likely should lower MAX_TIMEOUT in cases where we expect timeouts)

**Comment by hm1298** [comment]
simply the "check for missing IDs" part was taking over 60 seconds on my computer after downloading a lot of data--old implementation could open the same chunk multiple times, meaning for large users the program would unpack the same JSON too many times. even when there was nothing to update! fixed with latest commit

i don't have any noteworthy remaining performance issues given the API structure and how we store data. closing!
