### ISSUE TITLE
unit testing

### ISSUE THREAD

**Issue by naomiburks** [naomiburks/hanabdata#6]
do we want to do unit testing? I've been refactoring code a little irresponsibly without making sure that it still works

**Comment by hm1298** [comment]
this sounds important, yeah. I'll have to do some reading before I implement

**Comment by naomiburks** [comment]
i have some experience with pytest. i think the main thing to decide regardless of testing package is where to store tests: from prior reading the options are basically "keep them in the code" and "duplicate your folder structure and put tests in the dupe", and tbh i kinda hate both

**Comment by hm1298** [comment]
pytest sounds great. I've only used unittest before, but pytest looks so much friendlier

I guess I lean slightly on the "duplicate your folder structure" side, but I'm fine either way. we probably should make new tests as we go, but either implementation could satisfy the quality I want: at a glance, the general idea which modules have testing implemented already.

holding off on another code restructure until we decide this

**Comment by naomiburks** [comment]
Go for it
